version: 2
jobs:
 build:
   machine: true
   steps:
     - checkout 

     # build image
     - run: |         
         docker info
         docker build -t moviesdb-mvc -f Dockerfile .
     # deploy the image
     - run: |         
         docker login --username=senierharold@gmail.com --password=1ffe0f5a-7554-4c31-8f9e-2969f233393e registry.heroku.com
         docker tag moviesdb-mvc registry.heroku.com/moviesdb-mvc/web
         docker push registry.heroku.com/moviesdb-mvc/web                
         curl https://cli-assets.heroku.com/install.sh | sh
         heroku container:release web -a moviesdb-mvc
